<section class="full-editorial principles"><img data-parallax src="{{ $asset('assets/home-sustainability.webp') }}" alt="Người mẫu với thiết kế thêu thủ công giữa khung cảnh thiên nhiên" loading="lazy" width="1600" height="1067"><div><p class="eyebrow">CHỌN ÍT HƠN. YÊU LÂU HƠN.</p><h2 data-word-reveal>Đẹp trong lựa chọn.<br><em>Bền trong yêu thương.</em></h2><p>Chúng tôi tin vào những món đồ có thể đồng hành qua nhiều mùa. Một thiết kế được chăm chút, một lựa chọn có ý nghĩa với bạn.</p><button class="text-link" data-open="fashion-care">Cách chăm sóc thiết kế</button></div></section>
<section class="worlds section-pad" id="fashion-worlds"><header><p class="eyebrow">THẾ GIỚI TG THANG</p><h2 data-word-reveal>Ba cảm hứng.<br><em>Một dấu ấn.</em></h2></header><div class="worlds-grid">
    @foreach([['poppy', 'Hoa nở', 'Những cánh hoa hoang dại, một khu vườn được giữ lại trong từng sợi chỉ.', 'fashion-poppy'], ['thermal', 'Giao sắc', 'Sắc màu gặp gỡ, những đường nét hòa vào nhịp điệu của riêng bạn.', 'fashion-thermal'], ['woven', 'Dệt mơ', 'Chất liệu, đường nét và cảm giác — một cuộc đối thoại đầy tinh tế.', 'fashion-bespoke']] as $i => [$image, $name, $copy, $target])
        <a class="world-tile" href="#{{ $target }}"><div class="world-media"><img src="{{ $asset('assets/home-world-' . $image . '.webp') }}" alt="Cảm hứng {{ $name }} của TG Thang" loading="lazy" width="1000" height="1200"><video muted loop playsinline preload="none" data-hover-video data-src="{{ $asset('assets/worlds-' . ($i + 1) . '.mp4') }}"></video></div><h3>{{ $name }}</h3><p>{{ $copy }}</p><span class="text-link">Khám phá {{ $name }} ↗</span></a>
    @endforeach
</div></section>
<section class="heritage split-editorial" id="fashion-heritage"><div class="editorial-photo"><img data-parallax src="{{ $asset('assets/home-heritage.webp') }}" alt="Khung cảnh thiên nhiên, nguồn cảm hứng của atelier" loading="lazy" width="1000" height="800"></div><div class="editorial-copy"><p class="eyebrow">CÂU CHUYỆN CỦA ATELIER</p><h2 data-word-reveal>Từ cảm hứng<br><em>đến dấu ấn.</em></h2><p>TG Thang bắt đầu từ một ý tưởng giản dị: đưa cảm xúc vào những món đồ chúng ta mang theo mỗi ngày. Không vội vàng, không rập khuôn — chỉ có sự tò mò và những đôi tay yêu cái đẹp.</p><ol class="journey"><li><span>01</span><div><h3>Quan sát</h3><p>Tìm cảm hứng trong thiên nhiên và cuộc sống.</p></div></li><li><span>02</span><div><h3>Thử nghiệm</h3><p>Để màu sắc và chất liệu cùng kể chuyện.</p></div></li><li><span>03</span><div><h3>Hoàn thiện</h3><p>Một thiết kế sẵn sàng đồng hành với bạn.</p></div></li></ol></div></section>
<section class="gallery section-pad" id="fashion-gallery"><header><p class="eyebrow">NHỮNG KHOẢNH KHẮC CỦA ATELIER</p><h2 data-reveal>@tgthang.atelier</h2><p>Một chút cảm hứng mỗi ngày.</p></header><div class="gallery-window"><div class="gallery-track">@for($group = 0; $group < 2; $group++)<div class="gallery-group" @if($group) aria-hidden="true" inert @endif>@for($i = 1; $i <= 10; $i++)<button data-gallery="{{ $asset('assets/instagram-' . $i . '.webp') }}" data-caption="Khoảnh khắc atelier {{ $i }}" aria-label="Xem ảnh atelier {{ $i }}" @if($group) tabindex="-1" @endif><img src="{{ $asset('assets/instagram-' . $i . '.webp') }}" alt="Khoảnh khắc thời trang và chi tiết thiết kế {{ $i }}" loading="lazy" width="640" height="640"></button>@endfor</div>@endfor</div></div></section>
<section class="values section-pad"><p class="eyebrow">TINH THẦN CỦA TG THANG</p><h2 data-word-reveal>Được tạo nên từ những điều nhỏ.</h2><div><span data-reveal>THỦ CÔNG</span><span data-reveal>CÁ TÍNH</span><span data-reveal>TỈ MỈ</span></div></section>
