<!doctype html>
<html lang="vi">
<head>
  <meta charset="utf-8"/><meta name="viewport" content="width=device-width,initial-scale=1"/>
  <meta name="theme-color" content="#f8f8f2"/>
  <meta name="description" content="Lumi Academy — demo khóa học sáng tạo web 3D. Học qua thực hành, khám phá phòng 3D và thử một bài học tương tác."/>
  <title>Lumi Academy — Ý tưởng của bạn, một chiều không gian mới.</title>
  <link rel="icon" href="{{ Theme::asset()->url('assets/lumi.svg') }}" type="image/svg+xml"/>
  <link rel="stylesheet" href="{{ Theme::asset()->url('styles.css?v=10') }}"/>
  <script src="{{ Theme::asset()->url('course-data.js?v=4') }}" defer></script><script src="{{ Theme::asset()->url('app.js?v=9') }}" defer></script>
  <script src="{{ Theme::asset()->url('assets/scene.bundle.js?v=4') }}" defer></script>
</head>
<body>
  <a class="skip-link" href="#main">Đi đến nội dung</a>
  <header class="site-header">
    <a class="brand" href="#home" aria-label="Lumi Academy — Trang chủ"><img src="{{ Theme::asset()->url('assets/lumi.svg') }}" width="36" height="36" alt=""/><span>lumi<span class="brand-dot">.</span><small>ACADEMY</small></span></a>
    <nav aria-label="Điều hướng chính"><a href="#journey">Lộ trình</a><a href="#projects">Dự án</a><a href="#pricing">Khóa học</a><a href="#faq">Hỏi đáp</a></nav>
    <button class="button small" data-preview>Học thử miễn phí <span>↗</span></button>
    <button class="menu-toggle" aria-label="Mở menu" aria-expanded="false" aria-controls="mobile-menu">☰</button>
  </header>
  <nav id="mobile-menu" class="mobile-menu" aria-label="Điều hướng điện thoại" hidden><a href="#journey">Lộ trình học</a><a href="#projects">Dự án thực hành</a><a href="#pricing">Chọn khóa học</a><a href="#faq">Hỏi đáp</a><button data-preview>Học thử miễn phí ↗</button></nav>
  <main id="main">
    <section id="home" class="hero">
      <div class="hero-copy" data-scroll="hero">
        <p class="eyebrow"><span class="status-dot"></span> A LITTLE CODE. A WHOLE NEW WORLD.</p>
        <h1>Biến ý tưởng<br/>thành <span class="blue-text">thế giới<br class="desktop-break"/> 3D<span class="orange-text">.</span></span></h1>
        <p class="hero-description">Bắt đầu từ những dòng code nhỏ.<br/>Tạo nên những trải nghiệm khiến người khác<br class="desktop-break"/> muốn dừng lại và khám phá.</p>
        <div class="hero-cta"><a class="button" href="#pricing">Bắt đầu hành trình <span>↗</span></a><button class="play-link" data-preview><span class="play-icon">▷</span> Thử một bài học</button></div>
        <div class="hero-details"><span><b>56</b> bài học mẫu</span><i></i><span><b>24</b> giờ lộ trình</span><i></i><span>Học bằng <b>thực hành</b></span></div>
      </div>
      <div class="scene-shell">
        <div class="scene-top"><span class="scene-label"><i></i> <span id="scene-title">01 / GÓC SÁNG TẠO</span></span><button id="motion-toggle" aria-label="Tạm dừng hoạt ảnh" aria-pressed="false">Ⅱ</button></div>
        <div id="scene-host" class="scene-host" role="img" aria-label="Phòng học 3D có bàn máy tính, ghế, cây xanh và các hình khối sáng tạo"><div class="scene-fallback"><span class="fallback-cube"></span><p>Một góc nhỏ.<br/>Vô vàn ý tưởng.</p></div></div>
        <span class="scene-sticker" data-parallax="-90" data-turn="-30">made of<br/><b>possibilities ✳</b></span>
        <div class="scene-bottom"><div class="scene-navigation"><button id="scene-prev" aria-label="Cảnh trước">←</button><span id="scene-number">01 <i>/ 03</i></span><button id="scene-next" aria-label="Cảnh tiếp theo">→</button></div><span class="drag-hint">↔ KÉO ĐỂ XOAY · CUỘN ĐỂ KHÁM PHÁ</span><div class="palette" role="group" aria-label="Chọn màu cảnh"><button data-color="blue" aria-label="Màu xanh" aria-pressed="true"></button><button data-color="peach" aria-label="Màu cam đào" aria-pressed="false"></button><button data-color="mint" aria-label="Màu bạc hà" aria-pressed="false"></button></div></div>
        <p id="scene-status" class="sr-only" role="status"></p>
      </div>
      <a class="hero-scroll" href="#why">KHÁM PHÁ NHỮNG GÌ BẠN CÓ THỂ TẠO RA <span>↓</span></a>
    </section>
    <div class="skill-ribbon" data-scroll="ribbon" aria-label="Công cụ được giới thiệu trong lộ trình"><div aria-hidden="true">THREE.JS <span>✳</span> CREATIVE CODING <span>✳</span> WEB DESIGN <span>✳</span> BLENDER <span>✳</span> JAVASCRIPT <span>✳</span> THREE.JS <span>✳</span> CREATIVE CODING <span>✳</span> WEB DESIGN <span>✳</span> BLENDER <span>✳</span> JAVASCRIPT <span>✳</span></div></div>
    <section id="why" class="why section-pad">
      <div class="section-heading" data-reveal><p class="eyebrow">01 / KHÔNG CHỈ LÀ MỘT KHÓA HỌC</p><h2>Một kỹ năng mới.<br/><span class="muted-text">Một cách sáng tạo mới.</span></h2></div>
      <div class="why-grid"><p class="why-intro" data-reveal>Website có thể là một không gian để khám phá. Lumi giúp bạn đi từ <strong>“mình có một ý tưởng”</strong> đến <strong>“mình đã làm được nó”</strong>.</p><article data-reveal><span class="benefit-icon" data-parallax="-70" data-turn="90">↗</span><h3>Học đến đâu,<br/>tạo đến đó.</h3><p>Mỗi chặng kết thúc bằng một sản phẩm. Từ một vật thể chuyển động đến cả một thế giới nhỏ.</p></article><article data-reveal><span class="benefit-icon mint" data-parallax="60" data-turn="-130">✳</span><h3>Code có logic.<br/>Sáng tạo có không gian.</h3><p>Bài học đi từ nền tảng JavaScript đến ánh sáng, vật liệu và cách tạo tương tác.</p></article></div>
    </section>
    <section id="journey" class="journey section-pad">
      <div class="section-heading row" data-reveal><div><p class="eyebrow">02 / LỘ TRÌNH CỦA BẠN</p><h2>Đi từng bước.<br/><span class="blue-text">Đến những điều lớn hơn.</span></h2></div><p>Không cần biết 3D từ trước.<br/>Chỉ cần nền tảng JavaScript<br/>và một chút tò mò.</p></div>
      <div class="journey-layout"><aside class="journey-visual"><div class="journey-art" aria-hidden="true"><div class="orbit orbit-one"></div><div class="orbit orbit-two"></div><div class="journey-sphere"></div><div class="journey-cube"></div><div class="journey-star">✳</div><span class="art-axis axis-x">X</span><span class="art-axis axis-y">Y</span><span class="art-axis axis-z">Z</span></div><span class="eyebrow" id="chapter-label">CHƯƠNG 01 / NỀN TẢNG</span><h3 id="chapter-title">Chào thế giới 3D.</h3><p id="chapter-summary">Từ một trang web trống đến cảnh 3D đầu tiên.</p><div class="chapter-meter" aria-hidden="true"><i></i></div></aside><div id="curriculum" class="curriculum"></div></div>
      <p class="demo-note">Lộ trình concept gồm 56 bài, 24 giờ. Bản demo có bài học thử tương tác; chưa có thư viện video thương mại.</p>
    </section>
    <section id="projects" class="projects section-pad"><div class="projects-stage">
      <div class="section-heading row" data-reveal><div><p class="eyebrow">03 / BIẾN KIẾN THỨC THÀNH SẢN PHẨM</p><h2>Đừng chỉ học.<br/><span class="blue-text">Hãy làm điều thú vị.</span></h2></div><div class="project-navigation"><button id="project-prev" aria-label="Dự án trước">←</button><button id="project-next" aria-label="Dự án tiếp theo">→</button></div></div>
      <div class="project-window"><div class="project-track">
        <button class="project-card" data-project="0"><div class="project-art art-room"><div class="mini-window"></div><div class="mini-monitor">&lt;/&gt;</div><div class="mini-table"></div><span class="mini-plant">✳</span><span class="project-open">↗</span></div><small>01 / GEOMETRY · ÁNH SÁNG</small><h3>Một góc của riêng bạn.</h3><p>Thiết kế căn phòng đầu tiên bằng code.</p></button>
        <button class="project-card" data-project="1"><div class="project-art art-orbit"><div class="mini-orbit"></div><span class="mini-planet"></span><i class="mini-moon"></i><span class="project-open">↗</span></div><small>02 / PARTICLES · ANIMATION</small><h3>Vũ trụ trong trình duyệt.</h3><p>Viết nên những quỹ đạo đầy màu sắc.</p></button>
        <button class="project-card" data-project="2"><div class="project-art art-wave"><div class="wave-lines"></div><span class="wave-ball"></span><span class="project-open">↗</span></div><small>03 / SHADER · TƯƠNG TÁC</small><h3>Chuyển động thành cảm xúc.</h3><p>Khám phá bề mặt và những dải sóng.</p></button>
      </div></div><p class="demo-note">Ba ý tưởng trong nhóm sáu dự án thực hành. Bấm để xem mục tiêu và kỹ thuật của từng dự án.</p><div class="project-scroll-info"><span>CUỘN ĐỂ KHÁM PHÁ <b>↓</b></span><div class="project-meter" aria-hidden="true"><i></i></div><span id="project-position">01 / 03</span></div></div>
    </section>
    <section class="learning section-pad">
      <div class="learning-copy" data-reveal><p class="eyebrow">04 / HỌC THEO NHỊP CỦA BẠN</p><h2>Một chút mỗi ngày.<br/><span class="blue-text">Một bước tiến mỗi lần.</span></h2><p>Gặp một khái niệm mới, tự tay thử nó và nhìn thấy kết quả. Mọi thứ bắt đầu từ một bài học nhỏ.</p><ul class="check-list"><li>Bài học chia thành từng bước dễ theo dõi</li><li>Mã mẫu đi cùng giải thích</li><li>Thực hành ngay với mô hình tương tác</li><li>Lộ trình từ nền tảng đến dự án hoàn chỉnh</li></ul><button class="button" data-preview>Vào lớp học thử <span>↗</span></button></div>
      <button data-scroll="lesson" class="lesson-window" data-preview="2" aria-label="Mở bài học thử: Cho hình khối chuyển động" data-reveal><div class="window-bar"><span>● ● ●</span><span>LUMI / PLAYGROUND</span><i>↗</i></div><div class="lesson-art"><span class="lesson-torus"></span><span class="lesson-cube"></span><span class="lesson-play">▷</span></div><div class="lesson-caption"><span class="eyebrow">BÀI HỌC THỬ / 03</span><h3>Cho hình khối chuyển động.</h3><div class="fake-timeline"><i></i></div><span>Học bằng cách tự tay thử →</span></div></button>
    </section>
    <section id="pricing" class="pricing section-pad">
      <div class="section-heading centered" data-reveal><p class="eyebrow">05 / CHỌN ĐIỂM BẮT ĐẦU</p><h2>Đầu tư cho<br/><span class="blue-text">phiên bản sáng tạo hơn.</span></h2><p>Chọn nền tảng, chọn chuyển động — hoặc cả hành trình.<br/>Giá và quyền truy cập dưới đây là minh họa cho giao diện.</p></div>
      <div class="pricing-grid">
        <article class="price-card" data-reveal><span class="eyebrow">01 / XÂY NỀN TẢNG</span><h3>Web 3D<br/>Foundation</h3><p>Bắt đầu từ con số 0 về 3D, tạo ra trải nghiệm web đầu tiên của bạn.</p><div class="price">1.490.000<span>đ</span></div><span class="price-detail">32 bài học · 14 giờ · 4 dự án</span><ul class="check-list"><li>Nền tảng Three.js</li><li>Geometry, ánh sáng & vật liệu</li><li>Camera & tương tác</li><li>Tối ưu & hoàn thiện portfolio</li></ul><button class="button outline" data-plan="foundation">Chọn Foundation <span>↗</span></button></article>
        <article class="price-card featured" data-reveal><span class="popular-label">CẢ HÀNH TRÌNH ✳</span><span class="eyebrow">02 / MỞ RỘNG KHẢ NĂNG</span><h3>Creative Developer<br/>Bundle</h3><p>Từ hình khối đầu tiên đến những trải nghiệm mang dấu ấn của riêng bạn.</p><div class="price">2.290.000<span>đ</span></div><span class="price-detail">56 bài học · 24 giờ · 6 dự án</span><ul class="check-list"><li>Toàn bộ Web 3D Foundation</li><li>Toàn bộ Motion & Shaders</li><li>Đủ lộ trình từ cơ bản đến nâng cao</li><li>Tiết kiệm 490.000đ so với hai gói lẻ</li></ul><button class="button" data-plan="bundle">Chọn cả hành trình <span>↗</span></button></article>
        <article class="price-card" data-reveal><span class="eyebrow">03 / THÊM CHUYỂN ĐỘNG</span><h3>Motion<br/>& Shaders</h3><p>Dành cho bạn đã có nền tảng và muốn tạo những chuyển động mới.</p><div class="price">1.290.000<span>đ</span></div><span class="price-detail">24 bài học · 10 giờ · 2 dự án</span><ul class="check-list"><li>Particles & motion</li><li>Hoạt ảnh theo cuộn</li><li>Vật liệu & shader tùy biến</li><li>Hai dự án sáng tạo nâng cao</li></ul><button class="button outline" data-plan="motion">Chọn Motion & Shaders <span>↗</span></button></article>
      </div><p class="demo-note centered">Bản demo không thu tiền, không tạo tài khoản hay quyền truy cập khóa học thật.</p>
    </section>
    <section id="faq" class="faq section-pad"><div class="section-heading" data-reveal><p class="eyebrow">06 / MỘT VÀI ĐIỀU BẠN MUỐN BIẾT</p><h2>Trước khi<br/><span class="blue-text">bắt đầu.</span></h2><p>Thử một bài học để cảm nhận<br/>cách học có phù hợp với bạn.</p><button class="text-link" data-preview>Học thử ngay <span>↗</span></button></div><div class="faq-list">
      <details open><summary>Mình cần biết gì trước khi học?<span>+</span></summary><p>Nên biết biến, hàm, vòng lặp và sự kiện trong JavaScript. Bạn không cần biết Three.js hoặc Blender từ trước với gói Foundation.</p></details>
      <details><summary>Máy tính của mình có học được không?<span>+</span></summary><p>Dùng trình duyệt hỗ trợ WebGL và máy tính có thể chạy một trình soạn thảo code. Chất lượng render của demo tự giới hạn trên màn hình nhỏ; điện thoại phù hợp để xem và học thử.</p></details>
      <details><summary>Hai khóa học khác nhau như thế nào?<span>+</span></summary><p>Foundation gồm 32 bài về nền tảng và xây dự án. Motion & Shaders gồm 24 bài nâng cao. Bundle kết hợp cả hai thành lộ trình 56 bài.</p></details>
      <details><summary>Mình có thể xem bài học trước không?<span>+</span></summary><p>Có. Bấm “Học thử” để mở ba bài mẫu và tự điều khiển một hình khối 3D. Đây là nội dung tương tác, không phải video ghi hình.</p></details>
      <details><summary>Đăng ký trên trang này có thanh toán không?<span>+</span></summary><p>Không. Đây là website demo. Form chỉ tạo kết quả mẫu trong phiên xem và không gửi dữ liệu đi. Các khóa, giá và thời lượng là nội dung concept.</p></details>
    </div></section>
    <section class="final-cta" data-scroll="ending"><span class="end-orbit" data-parallax="-150" data-turn="80" aria-hidden="true"></span><p class="eyebrow" data-reveal>MỘT TRANG TRỐNG. VÔ VÀN KHẢ NĂNG.</p><h2 data-reveal>Ý tưởng tiếp theo.<br/><em>Là của bạn<span>✳</span></em></h2><button class="button light" data-preview>Bắt đầu bằng một bài học <span>↗</span></button><span class="end-caption">KEEP LEARNING. KEEP MAKING.</span></section>
  </main>
  <footer><a class="brand" href="#home"><img src="{{ Theme::asset()->url('assets/lumi.svg') }}" width="36" height="36" alt=""/><span>lumi.<small>ACADEMY</small></span></a><p>Một chiều không gian mới cho ý tưởng của bạn.</p><a href="#home">Về đầu trang ↑</a><div class="footer-bottom"><span>© 2026 LUMI ACADEMY / WEBSITE CONCEPT</span><span>Thương hiệu, khóa học và giá minh họa. Không thanh toán thật.</span></div></footer>
  <dialog id="preview-dialog" class="preview-dialog" aria-labelledby="preview-title"><button class="dialog-close" data-close aria-label="Đóng bài học">✕</button><div class="preview-sidebar"><span class="eyebrow">LUMI / LỚP HỌC THỬ</span><h2 id="preview-title">Bắt đầu<br/>từ một khối.</h2><div class="preview-tabs" role="tablist" aria-label="Bài học thử"><button role="tab" id="lesson-tab-0" aria-selected="true" aria-controls="lesson-panel" data-lesson="0">01 <span>Không gian 3D</span><i>↗</i></button><button role="tab" id="lesson-tab-1" aria-selected="false" aria-controls="lesson-panel" data-lesson="1" tabindex="-1">02 <span>Góc nhìn & hình khối</span><i>↗</i></button><button role="tab" id="lesson-tab-2" aria-selected="false" aria-controls="lesson-panel" data-lesson="2" tabindex="-1">03 <span>Cho khối chuyển động</span><i>↗</i></button></div><p>Ba bài thực hành mẫu.<br/>Tự tay thử, nhìn thấy kết quả.</p></div><div id="lesson-panel" class="lesson-panel" role="tabpanel" aria-labelledby="lesson-tab-0"><div class="preview-playground"><span class="playground-label">LIVE / YOUR FIRST OBJECT</span><div class="cube-space"><div id="practice-cube" class="practice-cube"><span class="face front">lumi.</span><span class="face back">✳</span><span class="face right">X</span><span class="face left">Y</span><span class="face top">Z</span><span class="face bottom">3D</span></div></div><div class="cube-controls"><label for="cube-angle">Góc xoay <output id="angle-value">25°</output></label><input id="cube-angle" type="range" min="-180" max="180" value="25"/><button id="cube-animate" aria-pressed="false">▷ Chạy hoạt ảnh</button></div></div><div class="lesson-text"><p class="eyebrow" id="lesson-count">BÀI 01 / 03</p><h3 id="lesson-title">Một điểm trong không gian.</h3><p id="lesson-description">Một vật thể 3D có vị trí theo ba trục: X (ngang), Y (dọc), Z (chiều sâu). Kéo thanh góc xoay để nhìn thấy các mặt khác nhau của hình khối.</p><pre><code id="lesson-code">cube.position.set(0, 0, 0);</code></pre><button id="lesson-next" class="button small">Bài tiếp theo <span>→</span></button></div></div></dialog>
  <dialog id="enroll-dialog" class="enroll-dialog" aria-labelledby="enroll-title"><button class="dialog-close" data-close aria-label="Đóng đăng ký">✕</button><p class="eyebrow">BẮT ĐẦU HÀNH TRÌNH / ĐĂNG KÝ MẪU</p><h2 id="enroll-title">Một lựa chọn.<br/><span class="blue-text">Nhiều khả năng.</span></h2><form id="enroll-form"><label for="selected-plan">Khóa học của bạn</label><select id="selected-plan" name="plan"><option value="foundation">Web 3D Foundation</option><option value="bundle">Creative Developer Bundle</option><option value="motion">Motion & Shaders</option></select><div class="enroll-summary"><span id="selected-facts">56 bài · 24 giờ</span><strong id="selected-price">2.290.000đ</strong></div><label for="learner-name">Tên của bạn</label><input id="learner-name" name="name" autocomplete="name" required maxlength="80" placeholder="Tên bạn muốn được gọi"/><label for="learner-email">Email</label><input id="learner-email" name="email" type="email" autocomplete="email" required maxlength="180" placeholder="ban@example.com"/><p class="demo-note">Form chỉ mô phỏng đăng ký trên trình duyệt. Không gửi thông tin, không thu tiền.</p><button class="button" type="submit">Tạo đăng ký mẫu <span>↗</span></button></form><div id="enroll-result" role="status" hidden></div></dialog>
  <dialog id="project-dialog" class="project-dialog" aria-labelledby="project-title"><button class="dialog-close" data-close aria-label="Đóng dự án">✕</button><p class="eyebrow" id="project-tag">DỰ ÁN 01</p><h2 id="project-title">Một góc của riêng bạn.</h2><p id="project-description"></p><ul id="project-skills" class="check-list"></ul><button class="button" data-preview>Thử những bước đầu tiên <span>↗</span></button></dialog>
  <noscript><p class="noscript-note">Bật JavaScript để xem cảnh 3D, lộ trình chi tiết và học thử. Bố cục và giá khóa học vẫn đọc được.</p></noscript>
</body>
</html>
