<section class="section section-gray" id="gym-contact">
    <div class="contact container">
        <div class="contact-photo"><img src="{{ $asset('assets/contact.webp') }}" alt="Không gian thể lực TG Thang minh họa" width="1181" height="1590" loading="lazy"><div class="contact-chips"><p><span>Email demo</span>hello@tgthang.example</p><p><span>Giờ mở cửa minh họa</span>06:00 – 22:00 · Mỗi ngày</p></div></div>
        <div class="contact-copy"><p class="eyebrow">BẮT ĐẦU CÙNG TG THANG</p><h2 data-reveal>Sẵn sàng<br><span>cho bước đầu?</span></h2><p>Chọn mục tiêu của bạn. Cùng biến buổi tập đầu tiên thành một khởi đầu đầy năng lượng.</p>
            <form id="gym-contact-form">
                <div class="form-row"><label>Họ và tên<input name="name" autocomplete="name" required maxlength="100" placeholder="Tên của bạn"></label><label>Email<input type="email" name="email" autocomplete="email" required maxlength="150" placeholder="ban@example.com"></label></div>
                <label>Bạn quan tâm đến<select name="service" id="gym-service"><option>Tập thử miễn phí</option><option>Huấn luyện cá nhân</option><option>Lớp tập nhóm</option><option>Tự do tập luyện</option><option>Đồng hành 1:1</option><option>Năng lượng nhóm</option></select></label>
                <label>Điều bạn muốn chia sẻ<textarea name="message" rows="3" maxlength="1000" placeholder="Mục tiêu hoặc khung giờ bạn muốn tập…"></textarea></label>
                <button class="button" type="submit">Đăng ký tập thử <span aria-hidden="true">↗</span></button><small>Biểu mẫu demo. Không gửi hoặc lưu thông tin.</small><p class="form-status" role="status"></p>
            </form>
        </div>
    </div>
</section>
<section class="cta-section"><span class="cta-watermark" aria-hidden="true">TG THANG</span><div class="container cta-grid"><div><h2 data-reveal>Đừng chờ<br>“một ngày nào đó”.</h2><p>Buổi tập tiếp theo có thể là khởi đầu của một thói quen mới.</p><a class="button button-white" href="#gym-contact">Bắt đầu hôm nay <span aria-hidden="true">↗</span></a></div><form id="gym-newsletter"><h3>Giữ nhịp năng lượng.</h3><p>Thử giao diện đăng ký nhận lịch tập và cảm hứng mới.</p><label for="gym-news-email">Email của bạn</label><div class="newsletter-row"><input id="gym-news-email" type="email" required autocomplete="email" placeholder="ban@example.com"><button class="button button-dark" type="submit" aria-label="Đăng ký nhận tin">↗</button></div><small>Đăng ký minh họa, không gửi email thực tế.</small><p role="status"></p></form></div></section>
<footer class="site-footer container"><div class="footer-grid"><div><a class="brand" href="#home"><img src="{{ $asset('assets/logo.svg') }}" alt="TG THANG" width="196" height="44" loading="lazy"></a><p>Mạnh mẽ hơn mỗi ngày.<br>Từ những bước nhỏ hôm nay.</p><small>TG Thang Fitness · Giao diện demo</small></div><nav aria-label="Khám phá"><h3>Khám phá</h3><a href="#gym-about">Về TG Thang</a><a href="#gym-services">Dịch vụ</a><a href="#gym-trainers">Huấn luyện viên</a><a href="#gym-plans">Gói hội viên</a></nav><nav aria-label="Kết nối"><h3>Kết nối</h3><button type="button" data-dialog="gym-schedule">Lịch tập</button><a href="#gym-faq">Câu hỏi thường gặp</a><a href="#gym-contact">Đăng ký tập thử</a><a href="{{ url('/theme-preview/?theme=gym') }}">Xem các giao diện</a></nav><div><h3>Không gian của bạn</h3><p>123 Đường Năng Lượng<br>TP. Hồ Chí Minh</p><p>06:00 – 22:00 · Mỗi ngày</p><small>Địa chỉ và giờ mở cửa minh họa.</small></div></div><div class="footer-bottom"><span>© {{ date('Y') }} TG Thang Fitness.</span><a href="#home">Về đầu trang ↑</a></div></footer>
