<!doctype html>
<html lang="vi">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width,initial-scale=1" />
  <meta name="description" content="An Nhiên Residence — bản demo dự án căn hộ ven biển tại Đà Nẵng. Khám phá ý tưởng kiến trúc, tiện ích và mặt bằng căn hộ." />
  <meta name="theme-color" content="#35112b" />
  <title>An Nhiên Residence — Chốn về bên biển</title>
  <link rel="icon" href="{{ Theme::asset()->url('assets/mark.svg') }}" type="image/svg+xml" />
  <link rel="preload" href="{{ Theme::asset()->url('assets/cormorant-garamond.ttf') }}" as="font" type="font/ttf" crossorigin />
  <link rel="preload" href="{{ Theme::asset()->url('assets/hero-day.webp') }}" as="image" />
  <link rel="stylesheet" href="{{ Theme::asset()->url('styles.css?v=13') }}" />
  <script src="{{ Theme::asset()->url('motion.js?v=13') }}" defer></script>
  <script src="{{ Theme::asset()->url('scroll-effects.js?v=12') }}" defer></script>
  <script src="{{ Theme::asset()->url('script.js?v=13') }}" defer></script>
</head>
<body>
  <a class="skip-link" href="#main">Đi đến nội dung</a>
  <header class="site-header">
    <a class="brand" href="#trangchu" aria-label="An Nhiên Residence — Trang chủ">
      <svg class="brand-ring" viewBox="0 0 100 100" aria-hidden="true"><defs><path id="ring" d="M50 10a40 40 0 1 1-.1 0"/></defs><text><textPath href="#ring">AN NHIÊN • RESIDENCE • ĐÀ NẴNG • </textPath></text></svg>
      <svg class="brand-flower" viewBox="0 0 100 100" fill="none" stroke="currentColor" stroke-width="1.4" aria-hidden="true"><g transform="translate(50 50)"><path id="brand-petal" d="M0 0C-17-13-11-27 0-35C11-27 17-13 0 0Z"/><use href="#brand-petal" transform="rotate(45)"/><use href="#brand-petal" transform="rotate(90)"/><use href="#brand-petal" transform="rotate(135)"/><use href="#brand-petal" transform="rotate(180)"/><use href="#brand-petal" transform="rotate(225)"/><use href="#brand-petal" transform="rotate(270)"/><use href="#brand-petal" transform="rotate(315)"/></g></svg>
    </a>
    <nav class="header-actions" aria-label="Điều hướng nhanh">
      <a class="select-home" href="#canho">CHỌN<br/>CĂN HỘ</a>
      <button class="small-action" data-enquiry>ĐẶT LỊCH THAM QUAN ↗</button>
      <button class="menu-button" id="menu-button" aria-haspopup="dialog">MENU <span aria-hidden="true">☰</span></button>
    </nav>
  </header>
  <aside class="scroll-rail" aria-hidden="true"><span id="scroll-number">00</span><div><i id="scroll-meter"></i></div><span class="rail-label">CUỘN ĐỂ KHÁM PHÁ ↓</span></aside>
  <button class="motion-toggle" id="motion-toggle" aria-label="Tạm dừng hiệu ứng" aria-pressed="false">Ⅱ</button>
  <main id="main">
    <section class="hero-sequence" id="trangchu" data-nav="light" aria-label="An Nhiên Residence tại Đà Nẵng">
      <div class="hero-stage">
        <div class="hero-images" aria-hidden="true"><img class="hero-day" src="{{ Theme::asset()->url('assets/hero-day.webp') }}" alt="" width="2400" height="1600" fetchpriority="high"/><img class="hero-sunset" src="{{ Theme::asset()->url('assets/hero-sunset.webp') }}" alt="" width="2400" height="1349"/></div>
        <div class="hero-shade"></div>
        <div class="hero-title">
          <p class="eyebrow">DỰ ÁN Ý TƯỞNG · ĐÀ NẴNG, VIỆT NAM</p>
          <h1>AN NHIÊN<br/><span>RESIDENCE</span></h1>
          <p class="hero-script">Chốn về bên biển</p>
          <div class="day-selector" role="group" aria-label="Chọn khung cảnh"><button data-view="day" aria-pressed="true">BAN NGÀY</button><i aria-hidden="true"></i><button data-view="sunset" aria-pressed="false">HOÀNG HÔN</button></div>
        </div>
        <p class="hero-motto left">MỘT NƠI ĐỂ SỐNG</p><p class="hero-motto right">MỘT CHỐN ĐỂ TRỞ VỀ</p>
        <div class="hero-hotspots">
          <div class="hotspot" data-image-x="0.155" data-image-y="0.48" hidden>
            <button class="hotspot-trigger" type="button" aria-label="Xem ảnh tòa căn hộ" aria-controls="tower-preview" aria-expanded="false"><span aria-hidden="true">+</span></button>
            <figure class="hotspot-preview" id="tower-preview" hidden><img src="{{ Theme::asset()->url('assets/hotspot-tower.webp') }}" alt="Cận cảnh tòa căn hộ với ban công kính trong banner" width="600" height="450"/><figcaption><small>AN NHIÊN RESIDENCE</small><strong>Tòa căn hộ</strong><span>Ban công thoáng mở, đón ánh sáng và gió biển.</span></figcaption></figure>
          </div>
          <div class="hotspot" data-image-x="0.666" data-image-y="0.66" hidden>
            <button class="hotspot-trigger" type="button" aria-label="Xem ảnh biệt thự sân vườn" aria-controls="villa-preview" aria-expanded="false"><span aria-hidden="true">+</span></button>
            <figure class="hotspot-preview" id="villa-preview" hidden><img src="{{ Theme::asset()->url('assets/hotspot-villa.webp') }}" alt="Cận cảnh biệt thự trắng và sân vườn trong banner" width="600" height="450"/><figcaption><small>AN NHIÊN RESIDENCE</small><strong>Biệt thự sân vườn</strong><span>Không gian riêng tư giữa những khoảng xanh.</span></figcaption></figure>
          </div>
        </div>
        <a class="hero-scroll" href="#tongquan">KHÁM PHÁ AN NHIÊN <span aria-hidden="true">↓</span></a>
        <span class="image-note">ẢNH ĐÀ NẴNG & KHÔNG GIAN SỐNG MINH HỌA</span>
      </div>
    </section>
    <section class="overview section-pad" id="tongquan" data-nav="dark">
      <div class="section-kicker"><span>01 / TỔNG QUAN</span><span>AN NHIÊN — MỘT NHỊP SỐNG KHÁC</span></div>
      <div class="intro-title"><h2>MỘT NƠI<br/>THUỘC VỀ <em>bạn.</em></h2><div class="intro-copy"><span class="tiny-symbol" aria-hidden="true">✳</span><p>Mở cửa đón gió biển. Khép lại những vội vàng.</p><p>An Nhiên là ý tưởng về một cộng đồng ven biển quy mô vừa đủ: riêng tư để nghỉ ngơi, gần gũi để kết nối và thoáng mở để mỗi ngày đều có một khoảng bình yên.</p><a class="text-link" href="#vitri">KHÁM PHÁ VỊ TRÍ <span>↗</span></a></div></div>
      <dl class="project-facts"><div><dt>CĂN HỘ TRONG CONCEPT</dt><dd><span data-count="84">84</span></dd></div><div><dt>KHỐI NHÀ</dt><dd><span data-count="3" data-digits="2">03</span></dd></div><div><dt>DIỆN TÍCH CĂN HỘ</dt><dd>58—168 <small>m²</small></dd></div><div><dt>KHÔNG GIAN MỞ DỰ KIẾN</dt><dd><span data-count="64">64</span><small>%</small></dd></div></dl>
      <p class="concept-note">Thông số ý tưởng thiết kế. An Nhiên Residence là dự án hư cấu phục vụ demo giao diện.</p>
    </section>
    <section class="coast-sequence" id="bien" data-nav="light" aria-label="Một chốn về bên biển">
      <div class="coast-stage">
        <div class="coast-picture"><img src="{{ Theme::asset()->url('assets/coast.webp') }}" alt="Bờ biển Đà Nẵng, ảnh minh họa bối cảnh" width="1600" height="899" loading="lazy"/><div class="coast-shade"></div></div>
        <span class="eyebrow coast-eyebrow">GIỮA NHỊP PHỐ VÀ NHỊP SÓNG</span>
        <h2>BIỂN Ở<br/><em>gần hơn.</em></h2>
        <p class="coast-description">Một buổi sáng có thể bắt đầu bằng gió biển.<br/>Một ngày có thể khép lại thật chậm, bên người thân.</p>
        <a class="coast-next" href="#vitri">KHÁM PHÁ KẾT NỐI <span>↓</span></a>
        <div class="coast-word" aria-hidden="true">ĐÀ NẴNG — AN NHIÊN — ĐÀ NẴNG</div>
        <div class="coast-progress" aria-hidden="true"><i></i></div>
      </div>
    </section>
    <section class="location section-pad" id="vitri" data-nav="dark">
      <div class="section-kicker"><span>02 / VỊ TRÍ & KẾT NỐI</span><span>ĐÀ NẴNG, VIỆT NAM</span></div>
      <div class="location-layout">
        <div class="location-copy"><h2>GẦN BIỂN.<br/>GẦN NHỮNG<br/><em>điều cần.</em></h2><p>Một ý tưởng sống ở phía đông Đà Nẵng: kết nối nhịp phố, khoảng xanh và đường bờ biển trong cùng một ngày.</p><div class="location-links" role="group" aria-label="Các điểm kết nối"><button data-location="beach" aria-pressed="true"><span>01</span> Biển Mỹ Khê <b>↗</b></button><button data-location="city" aria-pressed="false"><span>02</span> Trung tâm thành phố <b>↗</b></button><button data-location="airport" aria-pressed="false"><span>03</span> Sân bay Đà Nẵng <b>↗</b></button><button data-location="nature" aria-pressed="false"><span>04</span> Bán đảo Sơn Trà <b>↗</b></button></div></div>
        <div class="map-wrap"><img src="{{ Theme::asset()->url('assets/location-map.svg') }}" alt="Sơ đồ minh họa kết nối ven biển Đà Nẵng, không theo tỷ lệ" width="760" height="620" loading="lazy"/><span class="project-pin"><i>✳</i> AN NHIÊN<br/><small>VỊ TRÍ Ý TƯỞNG</small></span><button class="map-pin beach is-active" data-location="beach" aria-label="Xem kết nối Biển Mỹ Khê" aria-pressed="true">01</button><button class="map-pin city" data-location="city" aria-label="Xem kết nối Trung tâm thành phố" aria-pressed="false">02</button><button class="map-pin airport" data-location="airport" aria-label="Xem kết nối Sân bay Đà Nẵng" aria-pressed="false">03</button><button class="map-pin nature" data-location="nature" aria-label="Xem kết nối Bán đảo Sơn Trà" aria-pressed="false">04</button><div class="map-caption" aria-live="polite"><strong id="location-title">Biển Mỹ Khê</strong><p id="location-description">Những buổi sáng dạo biển, những chiều thả bước trên cát — một phần của nhịp sống ven bờ.</p></div></div>
      </div>
      <p class="concept-note">Sơ đồ kết nối ý tưởng, không thể hiện tọa độ hoặc thời gian di chuyển thực tế của một dự án.</p>
    </section>
    <section class="living-sequence" id="song" data-nav="dark" aria-label="Ba giá trị của An Nhiên">
      <div class="living-stage section-pad">
        <div class="section-kicker"><span>03 / KIẾN TRÚC & PHONG CÁCH SỐNG</span><span>MỘT NƠI ĐỂ THUỘC VỀ</span></div>
        <article class="living-step is-active"><div class="living-photo"><img src="{{ Theme::asset()->url('assets/architecture.webp') }}" alt="Ban công và mặt đứng một tòa căn hộ hiện đại, ảnh minh họa" width="1600" height="2400" loading="lazy"/></div><div class="living-copy"><span class="eyebrow">01 / KIẾN TRÚC</span><h2>THOÁNG MỞ<br/><em>để đón gió.</em></h2><p>Những ban công rộng, vật liệu ấm và khoảng mở đón ánh sáng. Kiến trúc hướng đến sự cân bằng giữa riêng tư và kết nối với thiên nhiên.</p><a class="text-link" href="#canho">KHÁM PHÁ CĂN HỘ <span>↗</span></a></div></article>
        <article class="living-step"><div class="living-photo"><img src="{{ Theme::asset()->url('assets/interior.webp') }}" alt="Không gian phòng khách đón ánh sáng tự nhiên, ảnh minh họa" width="1800" height="1350" loading="lazy"/></div><div class="living-copy"><span class="eyebrow">02 / KHÔNG GIAN SỐNG</span><h2>GIẢN ĐƠN<br/><em>để tận hưởng.</em></h2><p>Một góc đọc sách có nắng. Một bàn ăn đủ chỗ cho cả nhà. Không gian được hình dung từ những điều nhỏ làm nên một ngày dễ chịu.</p><a class="text-link" href="#thuvien">XEM KHÔNG GIAN <span>↗</span></a></div></article>
        <article class="living-step"><div class="living-photo"><img src="{{ Theme::asset()->url('assets/hero-day.webp') }}" alt="Cảnh quan xanh trong một khu nghỉ dưỡng Đà Nẵng, ảnh minh họa" width="2400" height="1600" loading="lazy"/></div><div class="living-copy"><span class="eyebrow">03 / CỘNG ĐỒNG</span><h2>GẦN NHAU<br/><em>vừa đủ.</em></h2><p>Đường dạo xanh nối những không gian gặp gỡ. Một cộng đồng quy mô vừa, nơi bạn có thể tìm thấy cả khoảng riêng và những cuộc trò chuyện thân quen.</p><a class="text-link" href="#tienich">KHÁM PHÁ TIỆN ÍCH <span>↗</span></a></div></article>
        <div class="chapter-controls" role="group" aria-label="Chọn giá trị"><button data-chapter="0" aria-pressed="true">01 — KIẾN TRÚC</button><button data-chapter="1" aria-pressed="false">02 — KHÔNG GIAN</button><button data-chapter="2" aria-pressed="false">03 — CỘNG ĐỒNG</button></div><div class="living-progress" aria-hidden="true"><i></i></div>
      </div>
    </section>
    <section class="amenities section-pad" id="tienich" data-nav="light">
      <div class="section-kicker"><span>04 / TIỆN ÍCH BÊN THỀM NHÀ</span><span>ĐỦ ĐẦY CHO MỖI NGÀY</span></div>
      <div class="amenity-layout"><div class="amenity-copy"><h2>SỐNG CHẬM<br/><em>hơn một chút.</em></h2><p>Chăm sóc sức khỏe. Dành thời gian cho người thân. Những trải nghiệm được đặt gần nhà, để ngày thường cũng có cảm giác như một kỳ nghỉ.</p><div class="amenity-options" role="group" aria-label="Chọn tiện ích"><button data-amenity="pool" aria-pressed="true"><span>01</span> Hồ bơi & sân nắng <b>↗</b></button><button data-amenity="garden" aria-pressed="false"><span>02</span> Đường dạo & vườn xanh <b>↗</b></button><button data-amenity="lounge" aria-pressed="false"><span>03</span> Lounge cộng đồng <b>↗</b></button><button data-amenity="wellness" aria-pressed="false"><span>04</span> Không gian wellness <b>↗</b></button></div></div><figure class="amenity-visual"><img id="amenity-image" src="{{ Theme::asset()->url('assets/pool.webp') }}" alt="Hồ bơi và sân nghỉ, ảnh tiện ích minh họa" width="1800" height="1200" loading="lazy"/><figcaption aria-live="polite"><span id="amenity-number">01 / 04</span><div><h3 id="amenity-title">Hồ bơi & sân nắng</h3><p id="amenity-description">Một khoảng xanh và mặt nước dành cho vận động nhẹ, thư giãn và những buổi chiều ở bên gia đình.</p></div></figcaption></figure></div>
      <p class="amenity-note">Tiện ích và hình ảnh minh họa theo ý tưởng thiết kế.</p>
    </section>
    <section class="homes section-pad" id="canho" data-nav="dark">
      <div class="section-kicker"><span>05 / CĂN HỘ & MẶT BẰNG</span><span>CHỌN KHÔNG GIAN PHÙ HỢP</span></div>
      <div class="homes-heading"><h2>KHÔNG GIAN<br/><em>cho câu chuyện riêng.</em></h2><p>Từ một tổ ấm gọn gàng đến không gian cho nhiều thế hệ. Mỗi lựa chọn bắt đầu từ cách bạn muốn sống.</p></div>
      <div class="home-tabs" role="tablist" aria-label="Loại căn hộ"><button id="tab-1pn" role="tab" aria-selected="true" aria-controls="home-panel" data-home="1pn">1 PHÒNG NGỦ <small>58 m²</small></button><button id="tab-2pn" role="tab" aria-selected="false" aria-controls="home-panel" tabindex="-1" data-home="2pn">2 PHÒNG NGỦ <small>84 m²</small></button><button id="tab-3pn" role="tab" aria-selected="false" aria-controls="home-panel" tabindex="-1" data-home="3pn">3 PHÒNG NGỦ <small>128–168 m²</small></button></div>
      <div class="home-panel" id="home-panel" role="tabpanel" aria-labelledby="tab-1pn"><div class="plan-visual"><img id="plan-image" src="{{ Theme::asset()->url('assets/plan-1pn.svg') }}" alt="Sơ đồ ý tưởng căn hộ 1 phòng ngủ, không theo tỷ lệ" width="680" height="540" loading="lazy"/><button class="plan-zoom" id="plan-zoom" aria-label="Phóng to mặt bằng căn hộ">PHÓNG TO <span>⤢</span></button></div><div class="home-information" aria-live="polite"><span class="eyebrow" id="home-code">AN / TYPE 01</span><h3 id="home-title">Một khoảng riêng<br/>thật vừa vặn.</h3><p id="home-description">Không gian gọn gàng cho một người hoặc đôi bạn, với phòng khách mở và ban công đón sáng.</p><dl><div><dt>Diện tích minh họa</dt><dd id="home-area">58 m²</dd></div><div><dt>Phòng ngủ</dt><dd id="home-bedrooms">01</dd></div><div><dt>Phòng tắm</dt><dd id="home-bathrooms">01</dd></div><div><dt>Khoảng ngoài trời</dt><dd>Ban công riêng</dd></div><div><dt>Gợi ý cho</dt><dd id="home-who">Cá nhân / cặp đôi</dd></div></dl><button class="text-link" data-enquiry>QUAN TÂM CĂN HỘ NÀY <span>↗</span></button><p class="concept-note">Sơ đồ minh họa, không theo tỷ lệ. Chưa có bảng giá hoặc giỏ hàng mở bán.</p></div></div>
      <a class="text-link brochure-link" href="{{ Theme::asset()->url('assets/ho-so-an-nhien.txt') }}" download>TẢI HỒ SƠ CONCEPT <span>↓</span></a>
    </section>
    <section class="materials-sequence" id="chitiet" data-nav="dark" aria-label="Chi tiết thiết kế và vật liệu">
      <div class="materials-stage section-pad">
        <div class="section-kicker"><span>06 / TỪNG CHI TIẾT NHỎ</span><span>CHẠM VÀO CẢM GIÁC Ở NHÀ</span></div>
        <div class="materials-heading"><h2>ĐẸP TỪ<br/><em>những điều gần gũi.</em></h2><p>Ánh sáng, bề mặt và khoảng thở.<br/>Ba lớp cảm hứng tạo nên một tổ ấm.</p></div>
        <div class="materials-window"><div class="materials-track">
          <article class="material-card"><div class="material-photo"><img src="{{ Theme::asset()->url('assets/interior.webp') }}" alt="Góc phòng khách ấm áp với vật liệu có tông màu tự nhiên, ảnh minh họa" width="1800" height="1350" loading="lazy"/></div><div class="material-copy"><span class="eyebrow">01 / BỀ MẶT</span><h3>Mộc mạc.<br/><em>Và ấm áp.</em></h3><p>Gỗ tông sáng, đá màu trung tính và bề mặt vải gợi cảm giác gần gũi. Bảng vật liệu ưu tiên sự hài hòa để không gian có thể đồng hành với nhiều phong cách sống.</p><span class="material-detail">GỖ SÁNG · ĐÁ TRUNG TÍNH · VẢI THÔ</span></div></article>
          <article class="material-card"><div class="material-photo"><img src="{{ Theme::asset()->url('assets/architecture.webp') }}" alt="Những ban công rộng của kiến trúc căn hộ, ảnh minh họa" width="1600" height="2400" loading="lazy"/></div><div class="material-copy"><span class="eyebrow">02 / KHOẢNG MỞ</span><h3>Để nắng<br/><em>ghé vào.</em></h3><p>Ban công như một căn phòng ngoài trời. Cửa mở lớn và khoảng đệm tạo nên sự chuyển tiếp giữa bên trong và cảnh quan, để ánh sáng trở thành một phần của nội thất.</p><span class="material-detail">BAN CÔNG · ÁNH SÁNG · KHOẢNG ĐỆM</span></div></article>
          <article class="material-card"><div class="material-photo"><img src="{{ Theme::asset()->url('assets/residence.webp') }}" alt="Không gian sống kết nối sân vườn và hồ bơi, ảnh minh họa" width="1800" height="1200" loading="lazy"/></div><div class="material-copy"><span class="eyebrow">03 / NHỊP SỐNG</span><h3>Riêng tư.<br/><em>Mà kết nối.</em></h3><p>Phòng ngủ là khoảng riêng yên tĩnh. Phòng khách và bàn ăn mở ra những cuộc trò chuyện. Đường dạo cùng sân chung tạo thêm cơ hội gặp gỡ bên ngoài căn hộ.</p><span class="material-detail">KHÔNG GIAN RIÊNG · SINH HOẠT CHUNG</span></div></article>
        </div></div>
        <div class="material-controls" role="group" aria-label="Chọn chi tiết thiết kế"><button data-material="0" aria-pressed="true">01 / BỀ MẶT</button><button data-material="1" aria-pressed="false">02 / KHOẢNG MỞ</button><button data-material="2" aria-pressed="false">03 / NHỊP SỐNG</button><span>CUỘN ĐỂ KHÁM PHÁ →</span></div>
        <p class="material-note">Định hướng thiết kế minh họa; không phải danh mục vật liệu bàn giao.</p>
      </div>
    </section>
    <section class="gallery-section section-pad" id="thuvien" data-nav="dark">
      <div class="section-kicker"><span>07 / THƯ VIỆN CẢM HỨNG</span><span>NHỮNG GÓC NHÌN AN NHIÊN</span></div><div class="gallery-heading"><h2>NHÌN THẤY<br/><em>nhịp sống mới.</em></h2><div class="gallery-filters" role="group" aria-label="Lọc thư viện"><button data-filter="all" aria-pressed="true">TẤT CẢ</button><button data-filter="space" aria-pressed="false">KHÔNG GIAN</button><button data-filter="landscape" aria-pressed="false">CẢNH QUAN</button></div></div>
      <div class="gallery-grid"><button class="gallery-card tall" data-gallery="architecture" data-category="space"><img src="{{ Theme::asset()->url('assets/architecture.webp') }}" alt="Ban công và mặt đứng kiến trúc hiện đại" width="1600" height="2400" loading="lazy"/><span><small>01 / KIẾN TRÚC</small> Những khoảng mở <b>↗</b></span></button><button class="gallery-card" data-gallery="interior" data-category="space"><img src="{{ Theme::asset()->url('assets/interior.webp') }}" alt="Phòng khách sáng với ghế sofa và cây xanh" width="1800" height="1350" loading="lazy"/><span><small>02 / NỘI THẤT</small> Nắng bên thềm nhà <b>↗</b></span></button><button class="gallery-card" data-gallery="pool" data-category="landscape"><img src="{{ Theme::asset()->url('assets/pool.webp') }}" alt="Mặt nước xanh của hồ bơi bên cây cối" width="1800" height="1200" loading="lazy"/><span><small>03 / TIỆN ÍCH</small> Một chiều thong thả <b>↗</b></span></button><button class="gallery-card wide" data-gallery="coast" data-category="landscape"><img src="{{ Theme::asset()->url('assets/coast.webp') }}" alt="Đường bờ biển Đà Nẵng lúc hoàng hôn" width="1600" height="899" loading="lazy"/><span><small>04 / ĐÀ NẴNG</small> Biển ở gần hơn <b>↗</b></span></button></div><p class="concept-note">Bộ ảnh cảm hứng từ Đà Nẵng và các không gian sống. Không phải ảnh của dự án An Nhiên thực tế.</p>
    </section>
    <section class="residents section-pad" id="cuocsong" data-nav="dark">
      <div class="section-kicker"><span>08 / MỘT NGÀY Ở AN NHIÊN</span><span>SỐNG THEO NHỊP CỦA BẠN</span></div>
      <div class="resident-heading"><h2>NGÀY THƯỜNG.<br/><em>Cũng đáng mong chờ.</em></h2><p>Từ một khoảng riêng đến những không gian chung. Một gợi ý về cách tận hưởng nhà, thay vì chỉ trở về để nghỉ.</p></div>
      <div class="resident-day">
        <article><span class="resident-time">06:30 <small>/ BUỔI SÁNG</small></span><div class="resident-photo"><img src="{{ Theme::asset()->url('assets/coast.webp') }}" alt="Bờ biển gợi cảm hứng cho một buổi sáng dạo bộ, ảnh minh họa" width="1600" height="899" loading="lazy"/></div><h3>Đón ngày<br/><em>từ phía biển.</em></h3><p>Một vòng đi bộ nhẹ, một tách cà phê ở ban công. Dành chút thời gian cho bản thân trước khi ngày mới bắt đầu.</p></article>
        <article><span class="resident-time">16:00 <small>/ BUỔI CHIỀU</small></span><div class="resident-photo"><img src="{{ Theme::asset()->url('assets/pool.webp') }}" alt="Hồ bơi trong cảnh quan xanh, ảnh minh họa" width="1800" height="1200" loading="lazy"/></div><h3>Thả chậm<br/><em>một nhịp.</em></h3><p>Vận động bên hồ bơi, đọc sách ở lounge hoặc cùng trẻ nhỏ khám phá sân vườn. Những khoảng nghỉ nằm gần nơi ở.</p></article>
        <article><span class="resident-time">19:00 <small>/ BUỔI TỐI</small></span><div class="resident-photo"><img src="{{ Theme::asset()->url('assets/lounge.webp') }}" alt="Phòng khách ấm cúng cho thời gian bên gia đình, ảnh minh họa" width="1600" height="1067" loading="lazy"/></div><h3>Giữ lại<br/><em>thời gian bên nhau.</em></h3><p>Một bữa cơm nhà, câu chuyện trong ngày và khoảng yên tĩnh sau cánh cửa. Không gian chung giúp gia đình ở gần nhau hơn.</p></article>
      </div>
      <div class="resident-services"><span class="eyebrow">ĐỊNH HƯỚNG VẬN HÀNH</span><p><strong>Tiếp đón cư dân</strong> tại sảnh chung.</p><p><strong>Quản lý không gian</strong> và chăm sóc cảnh quan.</p><p><strong>Kết nối cộng đồng</strong> qua các hoạt động tự nguyện.</p></div>
      <p class="concept-note">Lịch sinh hoạt và dịch vụ là gợi ý của concept, chưa có cam kết vận hành hoặc biểu phí thực tế.</p>
    </section>
    <section class="project-information section-pad" id="thongtin" data-nav="dark"><div class="section-kicker"><span>09 / THÔNG TIN DỰ ÁN</span><span>RÕ RÀNG TRƯỚC MỖI LỰA CHỌN</span></div><div class="information-layout"><div><h2>MỘT Ý TƯỞNG.<br/><em>Một khởi đầu.</em></h2><p>Giao diện này mô phỏng cách một dự án cung cấp thông tin cho khách hàng. Những dữ kiện thực tế cần được bổ sung từ chủ đầu tư trước khi sử dụng để kinh doanh.</p><dl class="information-facts"><div><dt>Tên concept</dt><dd>An Nhiên Residence</dd></div><div><dt>Bối cảnh</dt><dd>Đà Nẵng, Việt Nam</dd></div><div><dt>Trạng thái</dt><dd>Ý tưởng thiết kế / website demo</dd></div><div><dt>Chủ đầu tư & pháp lý</dt><dd>Chưa có hồ sơ thực tế</dd></div></dl></div><div class="faq"><details open><summary>An Nhiên có phải dự án đang mở bán? <span>+</span></summary><p>Chưa. Đây là thương hiệu và dự án hư cấu được tạo để trải nghiệm giao diện. Diện tích, số căn và tiện ích đều là thông số minh họa.</p></details><details><summary>Tôi có thể xem mặt bằng ở đâu? <span>+</span></summary><p>Phần “Căn hộ & mặt bằng” có ba lựa chọn 1–3 phòng ngủ. Bạn có thể đổi loại căn, phóng to sơ đồ và chọn loại căn khi thử đặt lịch.</p></details><details><summary>Giá, pháp lý và tiến độ có sẵn chưa? <span>+</span></summary><p>Chưa có giá bán, giấy phép, lịch bàn giao hoặc tiến độ thi công thực tế. Khi chuyển thành website dự án thật, khu vực này dùng để công bố hồ sơ và các cập nhật có nguồn xác nhận.</p></details><details><summary>Đặt lịch trên bản demo có gửi dữ liệu không? <span>+</span></summary><p>Không. Thông tin chỉ được dùng để hiển thị kết quả thử nghiệm trên trình duyệt hiện tại và không gửi đến bên thứ ba.</p></details></div></div></section>
    <section class="enquiry-section section-pad" id="lienhe" data-nav="light"><div class="section-kicker"><span>10 / BẮT ĐẦU CÂU CHUYỆN</span><span>ĐẶT LỊCH THAM QUAN</span></div><div class="enquiry-layout"><h2>CHỐN VỀ<br/><em>đang chờ bạn.</em></h2><div><p>Một cuộc trò chuyện để tìm hiểu không gian phù hợp với nhu cầu của bạn và gia đình.</p><button class="enquiry-button" data-enquiry>ĐẶT LỊCH THAM QUAN <span>↗</span></button><p class="enquiry-note">Trải nghiệm đặt lịch mẫu. Không tạo lịch hẹn thực tế.</p></div></div></section>
    <section class="closing" id="kettrang" data-nav="light"><div class="closing-stage"><img src="{{ Theme::asset()->url('assets/hero-sunset.webp') }}" alt="Biển Đà Nẵng trải dài dưới ánh hoàng hôn" width="2400" height="1349" loading="lazy"/><div class="closing-shade"></div><div class="closing-copy"><span class="eyebrow">ĐÀ NẴNG / VIỆT NAM</span><h2>MỘT CHỐN<br/><em>an nhiên.</em></h2><a href="#trangchu" class="closing-top">VỀ ĐẦU TRANG <span>↑</span></a></div></div></section>
  </main>
  <footer class="site-footer"><div><a class="footer-name" href="#trangchu">AN NHIÊN<br/>RESIDENCE</a><p>CHỐN VỀ BÊN BIỂN.</p></div><nav aria-label="Điều hướng cuối trang"><a href="#tongquan">Tổng quan</a><a href="#canho">Căn hộ & mặt bằng</a><a href="#thongtin">Thông tin dự án</a><button data-enquiry>Đặt lịch tham quan ↗</button></nav><div class="footer-bottom"><span>© 2026 AN NHIÊN / CONCEPT DEMO</span><p>Dự án hư cấu. Hình ảnh & thông số minh họa.</p><a href="{{ Theme::asset()->url('assets/sources.json') }}" target="_blank" rel="noopener">Nguồn hình ảnh ↗</a></div></footer>
  <dialog class="navigation-dialog" id="navigation" aria-labelledby="nav-title"><button class="dialog-close" data-close aria-label="Đóng menu">ĐÓNG ×</button><span class="eyebrow">AN NHIÊN RESIDENCE</span><h2 id="nav-title">CHỐN VỀ<br/><em>của bạn.</em></h2><nav aria-label="Các phần của website"><a href="#tongquan"><span>01</span> Tổng quan ↗</a><a href="#vitri"><span>02</span> Vị trí ↗</a><a href="#song"><span>03</span> Phong cách sống ↗</a><a href="#tienich"><span>04</span> Tiện ích ↗</a><a href="#canho"><span>05</span> Căn hộ & mặt bằng ↗</a><a href="#chitiet"><span>06</span> Chi tiết thiết kế ↗</a><a href="#thuvien"><span>07</span> Thư viện ↗</a><a href="#cuocsong"><span>08</span> Cuộc sống cư dân ↗</a><a href="#thongtin"><span>09</span> Thông tin dự án ↗</a><a href="#lienhe"><span>10</span> Đặt lịch tham quan ↗</a></nav><p>DỰ ÁN Ý TƯỞNG / ĐÀ NẴNG, VIỆT NAM</p></dialog>
  <dialog class="enquiry-dialog" id="enquiry-dialog" aria-labelledby="enquiry-title"><button class="dialog-close" data-close aria-label="Đóng đặt lịch">ĐÓNG ×</button><span class="eyebrow">AN NHIÊN / HẸN MỘT NGÀY AN NHIÊN</span><h2 id="enquiry-title">BẮT ĐẦU<br/><em>từ một cuộc hẹn.</em></h2><form id="enquiry-form"><div class="form-fields"><div><label for="visitor-name">Tên của bạn *</label><input id="visitor-name" name="name" autocomplete="name" required maxlength="80" placeholder="Nguyễn An"/></div><div><label for="visitor-phone">Số điện thoại di động *</label><input id="visitor-phone" name="phone" type="tel" autocomplete="tel" required placeholder="09xx xxx xxx" maxlength="20" aria-describedby="phone-hint"/><small id="phone-hint">Số di động Việt Nam, có thể dùng +84.</small></div><div><label for="visitor-home">Căn hộ quan tâm</label><select id="visitor-home" name="home"><option value="1pn">1 phòng ngủ · 58 m²</option><option value="2pn">2 phòng ngủ · 84 m²</option><option value="3pn">3 phòng ngủ · 128–168 m²</option><option value="undecided">Tôi cần thêm tư vấn</option></select></div><div><label for="visitor-date">Ngày muốn tham quan</label><input id="visitor-date" name="date" type="date"/></div></div><label class="consent"><input type="checkbox" required name="consent"/>Tôi hiểu đây là thao tác thử trên website demo, không tạo lịch hẹn thực tế.</label><button class="submit-button" type="submit">XÁC NHẬN LỊCH MẪU <span>↗</span></button><p class="form-note">Thông tin không được gửi đi hoặc lưu trên máy chủ.</p></form><div class="enquiry-success" id="enquiry-success" hidden role="status"><span aria-hidden="true">✳</span><h3>ĐÃ TẠO<br/><em>lịch tham quan mẫu.</em></h3><p id="success-copy"></p><p>Lịch này chỉ hiển thị trong phiên xem demo, không phải xác nhận từ đơn vị bán hàng.</p><button class="text-link" data-close>TIẾP TỤC KHÁM PHÁ <span>↗</span></button><button class="edit-enquiry" id="edit-enquiry">Chỉnh sửa thông tin</button></div></dialog>
  <dialog class="image-dialog" id="image-dialog" aria-labelledby="image-dialog-title"><button class="dialog-close" data-close aria-label="Đóng ảnh">ĐÓNG ×</button><img id="dialog-image" src="{{ Theme::asset()->url('assets/plan-1pn.svg') }}" alt=""/><div class="image-dialog-caption"><h2 id="image-dialog-title">Mặt bằng căn hộ</h2><span id="image-dialog-note">HÌNH ẢNH MINH HỌA</span></div><div class="gallery-navigation" id="gallery-navigation"><button id="gallery-prev" aria-label="Ảnh trước">←</button><span id="gallery-count">01 / 04</span><button id="gallery-next" aria-label="Ảnh tiếp theo">→</button></div></dialog>
  <noscript><p class="noscript">Trang vẫn đọc được khi tắt JavaScript. Bật JavaScript để đổi cảnh, chọn mặt bằng và dùng các tương tác.</p></noscript>
</body>
</html>
