<section class="people-section" id="spa-people">
    <div class="section-top"><div><p class="eyebrow">NHỮNG ĐÔI TAY TẬN TÂM</p><h2 data-reveal>Gặp người<br><em>chăm sóc bạn</em></h2></div><div class="slider-controls"><button type="button" data-slide="-1" aria-label="Chuyên viên trước">←</button><button type="button" data-slide="1" aria-label="Chuyên viên tiếp theo">→</button></div></div>
    <div class="people-track" tabindex="0" role="region" aria-label="Danh sách chuyên viên, kéo hoặc dùng phím mũi tên để xem">
        @foreach ([['Linh', 'Massage Bali & đá nóng', '6 NĂM KINH NGHIỆM'], ['Mai', 'Chăm sóc cơ thể & thảo mộc', '7 NĂM KINH NGHIỆM'], ['An', 'Nghi thức xông hơi', '5 NĂM KINH NGHIỆM'], ['My', 'Liệu trình cho hai người', '8 NĂM KINH NGHIỆM']] as [$name, $specialty, $experience])
            <article class="person"><img src="{{ $asset('assets/therapist-' . $loop->iteration . '.webp') }}" alt="Chuyên viên {{ $name }}" loading="lazy" width="480" height="700" draggable="false"><h3>{{ $name }}</h3><p>{{ $specialty }}</p><span class="eyebrow">{{ $experience }}</span></article>
        @endforeach
    </div>
    <p class="demo-note">Thông tin chuyên viên và mức giá là nội dung mẫu để giới thiệu giao diện.</p>
</section>
<section class="club-section" aria-label="Thẻ thành viên">
    <div class="club-marquee" aria-hidden="true"><span>AN YÊN · TG THANG SPA · AN YÊN · TG THANG SPA · </span><span>AN YÊN · TG THANG SPA · AN YÊN · TG THANG SPA · </span></div>
    <div class="club-orbit" aria-hidden="true"><img src="{{ $asset('assets/leaf.svg') }}" alt=""></div><div class="club-caption"><p class="eyebrow">TG THANG SPA CLUB</p><h2 data-reveal>Dành riêng<br><em>cho bạn.</em></h2><p>Thêm một lý do để dành thời gian cho bản thân.<br>Khám phá thẻ thành viên và những ưu đãi thư giãn.</p><button class="round-link" data-book="Thẻ thành viên" type="button">KHÁM PHÁ <span>↗</span></button></div>
</section>
<section class="gallery-section" id="spa-gallery"><div class="section-top"><p class="eyebrow">MỘT KHOẢNG LẶNG GIỮA PHỐ</p><h2 data-reveal>Không gian<br><em>của cảm xúc</em></h2></div><div class="gallery-grid">@foreach (['interior-1', 'interior-2', 'spa-portrait'] as $image)<button type="button" data-gallery="{{ $image }}" aria-label="Xem ảnh không gian {{ $loop->iteration }}"><img src="{{ $asset('assets/' . $image . '.webp') }}" alt="Không gian thư giãn {{ $loop->iteration }}" loading="lazy"><span>PHÓNG TO ↗</span></button>@endforeach</div></section>
<section class="faq-section" id="spa-faq"><div><p class="eyebrow">TRƯỚC KHI GHÉ THĂM</p><h2 data-reveal>Bạn muốn<br><em>biết thêm?</em></h2></div><div class="faq-list">@foreach ([['Mình cần đặt lịch trước không?', 'Bạn nên đặt lịch trước để chọn được khung giờ và liệu trình phù hợp. Form trên giao diện này chỉ mô phỏng thao tác đặt lịch.'], ['Nên đến trước lịch hẹn bao lâu?', 'Bạn có thể đến sớm khoảng 15 phút để nghỉ ngơi, thưởng thức một ly trà và trao đổi mong muốn chăm sóc với chuyên viên.'], ['Có liệu trình dành cho hai người không?', 'Có. Bạn có thể chọn phòng riêng và cùng trải nghiệm nghi thức thư giãn dành cho hai người.'], ['Thẻ quà tặng sử dụng như thế nào?', 'Người nhận có thể chọn liệu trình theo thẻ hoặc chọn trải nghiệm theo giá trị được tặng. Đây là nội dung mẫu để demo.']] as [$question, $answer])<details @if($loop->first) open @endif><summary>{{ $question }}<span aria-hidden="true">+</span></summary><p>{{ $answer }}</p></details>@endforeach</div></section>
<section class="closing-section" id="spa-contact"><img src="{{ $asset('assets/tea-hills.webp') }}" alt="Đồi trà xanh" loading="lazy"><div><p class="eyebrow">HẸN BẠN Ở MỘT KHOẢNG BÌNH YÊN</p><h2 data-reveal>Chậm lại<br><em>một chút.</em></h2><button class="round-link" data-book type="button">ĐẶT LỊCH <span>↗</span></button></div></section>
<footer class="spa-footer"><a class="brand" href="#spa-journey"><img src="{{ $asset('assets/logo.svg') }}" alt="TG THANG SPA" width="150" height="28"></a><p>MỖI NGÀY · 10:00–22:00<br>123 Nguyễn Văn Trỗi, TP. Hồ Chí Minh <span>(địa chỉ mẫu)</span></p><a href="mailto:hello@tgthang.example">hello@tgthang.example</a><span>© {{ date('Y') }} TG THANG SPA</span></footer>
